# Databricks notebook source
# MAGIC %md
# MAGIC # Red Bricks Insurance — Synthea Crosswalk (Phase 2)
# MAGIC
# MAGIC Maps Synthea-generated FHIR R4 patient bundles onto existing Red Bricks
# MAGIC MBR IDs, preserving all downstream joins. Writes rewritten bundles to
# MAGIC `clinical/fhir_bundles/` for downstream parsing by dbignite.
# MAGIC
# MAGIC **Input:** `{volume}/synthea_raw/fhir/` — Synthea FHIR bundles from Phase 1
# MAGIC **Output:** `{volume}/clinical/fhir_bundles/` — rewritten FHIR bundles with MBR IDs
# MAGIC
# MAGIC **Downstream:** `parse_fhir_with_dbignite.py` extracts Patient, Encounter,
# MAGIC Condition, and Observation Delta tables from the rewritten bundles.
# MAGIC
# MAGIC **Threading:** Bundle loading and FHIR file writes are parallelized with ThreadPoolExecutor.

# COMMAND ----------

dbutils.widgets.text("catalog", "main", "Catalog")
dbutils.widgets.text("schema", "red_bricks_insurance_dev", "Schema")

catalog = dbutils.widgets.get("catalog")
schema = dbutils.widgets.get("schema")
volume_base = f"/Volumes/{catalog}/{schema}/raw_sources"

print(f"Catalog: {catalog}, Schema: {schema}")
print(f"Volume base: {volume_base}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 1 — Load existing members and providers

# COMMAND ----------

from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

# Read members from Parquet (generated by run_data_generation.py)
df_members = spark.read.parquet(f"{volume_base}/members/")
members_data = [row.asDict() for row in df_members.collect()]
print(f"Members loaded: {len(members_data)} (MBR{members_data[0]['member_id'][-6:]}..MBR{members_data[-1]['member_id'][-6:]})")

# Read providers for NPI list
df_providers = spark.read.parquet(f"{volume_base}/providers/")
provider_npis = [row.npi for row in df_providers.select("npi").collect() if row.npi]
print(f"Providers loaded: {len(provider_npis)} NPIs")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 2 — Run crosswalk
# MAGIC
# MAGIC This is the core operation:
# MAGIC 1. Load all Synthea FHIR bundles (parallel I/O)
# MAGIC 2. Build 1:1 demographic crosswalk (Synthea UUID → MBR ID)
# MAGIC 3. Rewrite every bundle with MBR IDs, names, addresses
# MAGIC 4. Extract flat encounters/labs/vitals matching bronze schema
# MAGIC 5. Write all outputs to the volume (parallel I/O)

# COMMAND ----------

import os
import sys

# Add bundle/project root to path for imports
try:
    _here = os.path.dirname(os.path.abspath(__file__))
    _repo_root = os.path.abspath(os.path.join(_here, "..", ".."))
except NameError:
    _nb_path = dbutils.notebook.entry_point.getDbutils().notebook().getContext().notebookPath().get()
    _ws_root = "/Workspace" + _nb_path.rsplit("/src/notebooks/", 1)[0] if not _nb_path.startswith("/Workspace") else _nb_path.rsplit("/src/notebooks/", 1)[0]
    _repo_root = _ws_root
if _repo_root not in sys.path:
    sys.path.insert(0, _repo_root)

from src.data_generation.domains.synthea_crosswalk import run_crosswalk

synthea_fhir_dir = f"{volume_base}/synthea_raw/fhir"
max_workers = os.cpu_count() or 8

print(f"Synthea FHIR dir: {synthea_fhir_dir}")
print(f"Output volume: {volume_base}")
print(f"Max workers: {max_workers}")

summary = run_crosswalk(
    members_data=members_data,
    synthea_fhir_dir=synthea_fhir_dir,
    output_volume_base=volume_base,
    provider_npis=provider_npis,
    max_workers=max_workers,
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 3 — Validate outputs
# MAGIC
# MAGIC Verifies FHIR bundles were rewritten with MBR IDs. Downstream parsing
# MAGIC (encounters, labs, vitals, conditions) is handled by `parse_fhir_with_dbignite.py`.

# COMMAND ----------

import json

# Check FHIR bundles
fhir_path = f"{volume_base}/clinical/fhir_bundles/"
fhir_files = [f for f in os.listdir(fhir_path) if f.endswith(".json")]
print(f"FHIR bundle files: {len(fhir_files)}")

# Sample FHIR bundle — verify MBR ID rewrite
if fhir_files:
    with open(os.path.join(fhir_path, fhir_files[0]), "r") as f:
        sample_bundle = json.load(f)
    for entry in sample_bundle.get("entry", []):
        r = entry.get("resource", {})
        if r.get("resourceType") == "Patient":
            print(f"\nSample FHIR Patient.id: {r.get('id')}")
            print(f"Sample FHIR Patient.name: {r.get('name')}")
            ident = r.get("identifier", [{}])[0]
            print(f"Sample FHIR identifier system: {ident.get('system')}")
            print(f"Sample FHIR identifier value: {ident.get('value')}")
            break

    # Count resource types in sample
    resource_types = {}
    for entry in sample_bundle.get("entry", []):
        rt = entry.get("resource", {}).get("resourceType", "Unknown")
        resource_types[rt] = resource_types.get(rt, 0) + 1
    print(f"\nResource types in sample bundle: {json.dumps(resource_types, indent=2)}")
    print(f"\nNext: Run parse_fhir_with_dbignite.py to extract clinical tables")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Summary

# COMMAND ----------

print("=" * 60)
print("SYNTHEA CROSSWALK COMPLETE (Phase 2)")
print("=" * 60)
print(f"Crosswalk mappings: {summary['crosswalk_size']}")
print(f"FHIR bundles rewritten: {summary['bundles_rewritten']}")
print(f"\nOutputs written to: {volume_base}/clinical/")
print(f"  fhir_bundles/   -> {len(fhir_files)} JSON bundles")
print(f"\nNext: Run parse_fhir_with_dbignite.py to extract clinical tables into Delta")
